### PR TITLE
feat: allow opt-out of schema dump to dict

### LINKED ISSUE #56: Do not always dump pydantic models to dict
## Request:

When using pydantic models for events, they are dumped to dict by `fastapi-events`.

## Motivation

This is convenient but restrictive. A pydantic model is often more useful for a handler than a dict:

  - You can call `isinstance` on it. This is particularly useful for events where one handler callback handles multiple event types.
  - The model may have methods or other logic/data that isn't captured by dumping to dict.
  - You can get type hints in event handlers.

## Proposed API

Add arg `payload_schema_dump: bool = True` to `dispatch`.

The default behaviour is unchanged. When this is set to `False`, handlers are called with the pydantic model as the payload.

If `validate_payload is True`, we still do the round-trip to re-validate the payload, but skip the final dump.

### PR DESCRIPTION
**Pull request by psychedelicious**
- Adds `payload_schema_dump: bool = True` arg to `dispatch`, `_derive_event_name_and_payload_from_pydantic_model` and `_validate_payload`. When `False`, the event handlers are called "live" pydantic model for payload. The default behaviour is unchanged.
- Updates tests for this new functionality.

Closes #56

### CODE REVIEW

**Comment by melvinkcx** [comment]
I merged your #55 and it's causing merge conflict now. Please pull from the upstream again. 

BTW, I also noticed I didn't enable Gitlab Action on `pull_request`, I believe it should work once you have the latest upstream in your changes.

Again, thanks for your contribution.

**Comment by psychedelicious** [comment]
@melvinkcx Updated. 

Happy to contribute! 

Locally, I noticed `tox` is skipping a lot of the permutations of tests and I couldn't figure out how to get it to run everything - is this expected? It's my first time using tox.

```sh
flake8: OK (1.54=setup[1.42]+cmd[0.12] seconds)
  isort: OK (0.96=setup[0.89]+cmd[0.07] seconds)
  py37-starlite: SKIP (0.00 seconds)
  py38-starlite: SKIP (0.00 seconds)
  py39-starlite: SKIP (0.00 seconds)
  py310-starlite: OK (2.21=setup[0.98]+cmd[1.23] seconds)
  py311-starlite: SKIP (0.01 seconds)
  py37-fastapi092-pydantic1: SKIP (0.01 seconds)
  py37-fastapi093-pydantic1: SKIP (0.01 seconds)
  py37-fastapi094-pydantic1: SKIP (0.01 seconds)
  py37-fastapi095-pydantic1: SKIP (0.01 seconds)
  py37-fastapi096-pydantic1: SKIP (0.01 seconds)
  ... # snip
  congratulations :) (47.75 seconds)
```

**Comment by melvinkcx** [comment]
Yeah, tox runs tests based on the environment it's in. If it can't detect the Python version it needs, it will skip them. What you're seeing is normal.

**Review by melvinkcx — APPROVED** [review]
LGTM, thanks!

**Comment by psychedelicious** [comment]
Ah ok. Thanks for explaining how tox works. Nifty.

**Pull request merged**
